language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t unlearnt/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true unlearnt/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  name: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-915885604842"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


  http://dockerreact-env.eba-pssbuwkg.us-east-1.elasticbeanstalk.com/